export const USER_ACTION_TYPES = {
  SET_FINANCIAL_YEAR_AND_COUNTRY: "SET_FINANCIAL_YEAR_AND_COUNTRY",
  SET_INVESTMENT_LOGISTICS: "SET_INVESTMENT_LOGISTICS",
  SET_INVESTMENT_TYPE: "SET_INVESTMENT_TYPE",
};
